CONFIG_GPIO=y
CONFIG_USB_DEVICE_STACK_NEXT=y
CONFIG_USBD_CDC_ACM_CLASS=y


# shell
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
#CONFIG_UART_LINE_CTRL=y
CONFIG_SHELL=y
CONFIG_SHELL_BACKEND_SERIAL=y
CONFIG_SHELL_CMD_BUFF_SIZE=64


# logging
#CONFIG_LOG=n
#CONFIG_LOG_MODE_DEFERRED=y
#CONFIG_LOG_BACKEND_UART=y
#CONFIG_USBD_CDC_ACM_LOG_LEVEL_OFF=y
#CONFIG_LOG_BUFFER_SIZE=12000
#CONFIG_LOG_RUNTIME_FILTERING=y
#CONFIG_LOG_PRINTK=y

# C++
CONFIG_CPP=y
CONFIG_STD_CPP23=y
CONFIG_GLIBCXX_LIBCPP=y
CONFIG_REQUIRES_FULL_LIBCPP=y

# Enable Watchdog driver support
CONFIG_WATCHDOG=y
CONFIG_WDT_RPI_PICO=y

# inne
CONFIG_LED_STRIP=y
CONFIG_WS2812_STRIP_RPI_PICO_PIO=y
CONFIG_INPUT=y
CONFIG_INPUT_GPIO_KEYS=y
CONFIG_INPUT_GPIO_QDEC=y
CONFIG_SIZE_OPTIMIZATIONS=y
CONFIG_REBOOT=y
CONFIG_CLOCK_CONTROL=y
CONFIG_ZBUS=y

CONFIG_MAIN_STACK_SIZE=4096
CONFIG_ISR_STACK_SIZE=4096
CONFIG_IDLE_STACK_SIZE=4096
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=4096
